-- Adicionar coluna is_dubbed se nao existir
ALTER TABLE filmes ADD COLUMN IF NOT EXISTS is_dubbed BOOLEAN DEFAULT FALSE;

UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Chefe Não Finge Mais';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Últimas Palavras do Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Tive Um Bebe Sem Você';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Neto Falso? Não Verdadeiro';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mordida Do Destino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Sinfonia Bem Orquestrada Com Meu Patrão/Melodia do Verão Amoroso';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casados Num Piscar De Olhos e Totalmente Mimados';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Presa Pelo Amor Que Me Salvou';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Bela e o Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Noivo Trocado: Casei com um Chefão da Máfia';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sol Após As Cinzas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Desejo Proibido Do Intocável';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Eu Sou A Lenda';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Três golpes E Uma Pena De Adeus';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A LUNA PERDIDA DO REI LYCAN';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Alma Gêmea Indesejada [DUBLADO]';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Paixão Tabu Meu Meio Irmão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Primavera Que Não Voltou';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Surpresa Do Pai Rico';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Encontro Do Destino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sou Filha Do General';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Rainha Não Ama Só Conquista';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Vingança Carmesim: as Noivas Desaparecidas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Máscara Vingança';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Princesa Dos Laycan Não Será sua Luna';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Obesessão Da Máfia';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Dama Chefe Da Traída A Amada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Acidental Com Meu CEO Pobre';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Doutora e a Imperatriz';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Jogo Do Desejo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Reconquistando A Minha Ex Bilionária Esposa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Bilhete Que Ela Me Roubou';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Amor Fora De Serviço';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Mestre Oculto';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Vingança De Catarina';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'As Regras Da  Cowgirl Agora';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Uma Noite Só... Para Sempre';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Recompensa De Sangue A Herdeira Retorna';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Professor Meu Vício';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Apaixonado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Segredo Do Domínio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Esplendor De Um Pai';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Pai Do Meu Filho É O Tio Richard';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Em Dobro Pacto Dos Gêmeos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O CEO Que Comprou Meu Destino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Criando o Filho da Amante';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Relâmpago Minha Segunda Chance Aos 40';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Eu Posso Ouvir Seus Pensamentos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Segredos Do Coração ';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Chefe Legista Largou Tudo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Noiva Do Demônio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Volta Da Herdeira Caida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Paris Errada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Caminho Para A Felicidade';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'CASEI COM UM JARDINEIRO GANHEI UM PRÍNCIPE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DEPOIS DO TÉRMINO CASEI  COM O CHEFÃO DA MÁFIA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Esposa Mimada Do Figurão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Desejo Oculto do CEO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Encontrei Um Marido Multimilionário Para O Natal';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A NOITE ERRADA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Vingança Da Empregada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Esposa Troféu Ela é a Própria Fortuna';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Campeão De Box Renascido';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'De Volta Ao Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Jovem Que Queria Ser Juiz Para Se vingar';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Taxa De Cambio Do Destino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Te Amo Com O Coração Difícil De Tocar';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Papai, Por Que Me Deixou Morrer';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Retorno Com Tudo Minha Coroa Minha aliança';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Eu Sou Sua Tempestade Marido';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Prisioneiro Do Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Divorciada, Diretora De Volta';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'NOSSO LAR NOSSO AMOR';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Nascido Para Mestre';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Divórcio No Dia Do Parto';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Chefão Nao Agora so Quero Estudar';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'PRIMEIRO AMOR ÚLTIMA ESCOLHA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Ceo Quer Meu Pequeno Rascal';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DE ENVENENADA A INIMIGA IMPLACÁVEL';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Falso Casamento Dois Chefes';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Retorno Da Herdeira Gênio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'SETE IRMÃS PODEROSAS UM POUCO AQUÉM DO MEU PODER';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'HERDEIRA OCULTA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Esposa Amada Ceo Retorna';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Retorno Do Desaparecido';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Cativa Na Sua Gaiola';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Retorno da Herdeira';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Siga Minha Voz';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Vingança da Esposa Desesperada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Escuto Sua Voz';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sou a Mãe Dela Ajoelhe Se';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Ele Veio Por Mim';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Ex Mágico Entre Presas e Garras';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Marido Inesperado Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor a Margem';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Destino Selado Pacto Com O Rei Da Mafia';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Retorno da Herdeira';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'BENÇÃO DE CINCO MÃE FORTE PAI DESCONHECIDO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sem Você Vida Nota dez';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Amor Que Ele Deixou Desaparecer';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Noiva Predestinada Do Rei Alfa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Amante Secreto é Filho Da Minha Melhor Amiga';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Noiva Fuja do CEO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mentes Perversas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Quando O Amor Se Foi';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DA QUEDA NASCE A ASCENSÃO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Recompensa De Uma Boa Ação';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Limite Do Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Jogo Da Criada Astuta';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Protetor Meu Pecado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Coração Trancado Novo Começo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Professor Minha Obsessão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'CONTRATO DE CORAÇÕES';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'SÓ RESTAM AS ROSAS';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Uma Noite Com Meu Meio Irmão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Apressadamente Para O Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Rainha Não Amante';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Forçados A Casar Decidimos a Amar/Fim De Semana Exclusivo: Seu Amor Incessante/ O Caminho Da Silva Até o Seu Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Os Herdeiros Do CEO: A Fuga Da Esposa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Pureza Da Pele De Gelo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Encantadora é a Herdeira';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Minha Esposa XXL';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amando O Melhor Amigo Do Meu Irmão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Magnata Desmascarando: O Genro Dominante';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DA CHEFE À MADRASTA FILHO NÃO SURTA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Entre Segredos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Chefe Em Onda';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Renascida Mãe Poderosa e Imbatível';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Cunhado Meu Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Aterrissando no Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amar Você De Novo. Meu Irmao Adotivo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Você é Tudo O que Eu Quero';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sequestrada Pela Máfia';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Laços De Sangue';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MEU MARIDO ERA MEU AZAR';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Drama Do Banquete  De  Noivado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Eu Te Amo Mais Do Que A Vida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O PREÇO QUE PAGUEI PELO MEU AMOR';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Mistério Das Águas Termais';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O BRILHO DA SRTA JOANA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Bebê Gângster Papai Me Mima até o Paraíso';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Quadrigêmeos Do Tio Do Meu Ex';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mãe Solteira Por Engano Esposa Do CEO Por Destino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Quando a Promessa Se Rasga';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Da Sombra a Rainha';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Doce Esposa Dos Anos 80';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DANÇA DA VINGANÇA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Lendário Pai Retorna';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Seu Pleno Poder Nos 50';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MEU CHEFE O GAROTO DE PROGRAMA DE NATAL';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Estragada Pelo Meu Papai Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Bad Sister Irmã Do Pecado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Minha vida Na Máfia';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mentiras No Amor Verdades No Ódio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Uma Sexta Feira Mais Louca Ainda';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Pão Vence o Ouro Cai';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Superando Meu guarda Costas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Frequência Do Amor a 30000 Pés';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Gatilheiro';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Herdeira Renascida Das Cinzas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Cuidado Eu Sou a Chefona';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Pai Don';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Herdeira Bilionária Confronta Seu Marido Assassino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Desejo Sombrio Da Elise';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Nao Intimidade A Irmã Da Mestra Das Artes Marciais';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Entre a Filha e a Guerra';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Senhora Não Fuja';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Minha Pobre Ex, A Herdeira Bilionária';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A filha Da Casa Guardiã De Reinos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O AMOR QUE NÃO SOUBE CUIDAR';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Quando a Substituta Some';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Amor Secreto Era Meu Inimigo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Paz No Reino Caos No Coração';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sexo Para Reatar';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Minha Cura Começa Com Ela';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Esposa e Buff absurdo: Subindo Para dominar tudo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Nerd Dele';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Do Amor A Solidão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'ESSA DOUTORA É BRABA DEMAIS';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Fim Da Dona De Casa Maldita';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'ACRIMONIA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'AME ME OUTRA VEZ';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sra Dragão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Doceza Perdida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DE VOLTA EX SECRETO VENHA BUSCAR O HERDEIRO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DE PLANO B A AMOR DE VERDADE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'PAIS DESAMPARADOS SOU COSTA QUENTE DELES';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Traído Pelos Que Amava';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'minhas Versões De Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'ROSTOS IGUAIS QUEM É A VERDADEIRA NOIVA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Legado Perdido Do Chef Divino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Na Brisa Do Crepúsculo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Corrida De Volta Para Mim';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'POR SANGUE JURADO A ROSA ESPINHOSA DA MÁFIA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Resto Da Minha vida Será De Solidão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'RENASCIDA EM 1989';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Herdeira Deslumbrante';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O PONTO DE VIRADA DA MÃE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'De Arrasada A Raiar: Sou De Mais Sem Vocês';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Vingança Secreta Do Irmão Gêmeo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casados Num Piscar De Olhos E Totalmente Mimados';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Blindado: Um Contrato De Natal';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sem Retorno Sob As Estrelas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Afogamento De Paixão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Prometo The Dias Felizes';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Perdido';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'De Volta Ao Jogo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Já Tivemos Uma Casa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DE VOLTA AOS MEUS BRAÇOS MEU AMOR';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Por Favor Amarre Me tio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Charlotte e Os 7 Gostosões';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'IRMÃS RENASCIDAS MARIDOS TROCADOS';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Abismo Congelado do Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Me Ame Como Você Faz';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Diabo Veste Desejo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Preço Da Traição';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor nos Uniu De Novo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Pai Imbatível';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Cláusula Proibida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Secreto Com a Doce Esposa Da Sorte';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Implorando para que eu volte para casa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Herdeira Pôs O Marido Na Lista Negra';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Ja Que Você Nunca Foi Minha';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Corações Roubados';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = '7 ANOS EM 7 DIAS';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mulher Grávida, Mimada pelo Marido Rico';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mamãe eu Trouxe o Papai Pra Te Salvar';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Garota Do Interior Vs Dono Do Crime';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Par Perfeito Rejeitado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'CINDERELA E O SEGREDO DO POBRE MILIONÁRIO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Coração Traído';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Papai Campeão e Suas Filhas Da Sorte';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Você Tem um Homem';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Conseguir Um Marido Inestimável';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'NOITE PROIBIDA AMOR QUE NÃO SE APAGA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Sopro Primordial';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DE INVISÍVEL A IRRESISTÍVEL';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Retorno Triunfal Do Deus Infinito';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Felicidade Do Casamento Errado| Casamento Em Chamas| No Olho Da Tempestade| Armadilha Nupcial';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Queime Minha Gorda';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Acordar Casada Com Meu crush';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Segunda Chance Primeiro Mimo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Atrevida Impertinente';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Doces e Desforra/ Reencarnei Como Um Bebê  Fiz Meu Pai Virar Magnata';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'CASAR SE COM MILIONÁRIO APÓS DESPEDIR SE DO AMOR TÓXICO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'De Criada A Dona';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Entre Segredos e Mentiras';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Agente Secreta Que Enriquecia Com a Família';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Boa Menina Do Daddy Dom';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Fios Do Destino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'PROMESSAS DE AMOR DO CEO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Filho Do Meu Ex Marido é Meu Prazer Secreto';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Até Você Me Deixar';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Monarca';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Esposa Do CEO é a chefe Secreta';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'RENASCIDAS A ESCOLHA DO DESTINO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Caseira Expulsa: A Caipira Retorna Vitoriosa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Esposa Poderosa Renascida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Amor Plus Size Do MVP';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Adeus Ao Passado Ola Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DOMANDO O DESEJO IMPLACÁVEL DO MEU BILIONÁRIO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Renascendo Das Cinzas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'FELIZES ENTRE FLORES';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Tio Não Me Acalme';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Herdeira Retorna';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Fugir Do Meu Marido Destinado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'CHAMADA PELO MEU AMOR';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Faxineira Milionária';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Quebrando O Gelo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Que Não Volta Mais';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Verdade Sempre Vem Á Tona';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Primeiro Amor do Quarterback';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = '3 O Número Perfeito';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'AMOR A TODA VELOCIDADE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Melhor Céu Que O Supremo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'UAU MINHA ESPOSA MENDIGA É UMA LENDA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'EX-MARIDO 200KG DE ÓDIO PARA CALCULAR';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Eu vou Me Casar';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Novato Mais Forte Do Mundo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor dos Jogos: Despedida para Valer';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mamãe Tá Doendo, Cadê O Papai?';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Guerra Em Casa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Quem Vai Envelhecer Ao Seu Lado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Anjo No Espelho';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Menina Que Fala Com Os Animais';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Carregando Seus Bebês, Roubando Seu Coração';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Quando O Amor Apaga Memoria';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Coroa Além do Túmulo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Como O Sol Nascente/ Aurora Do Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Princesa Mimada Pela Família Rica';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Três Bênçãos Imperiais A Ascensão Da Fênix';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Princesa e General A Jornada Da Heroína';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A vingança Do Genro';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Punhos De Vingança Ela e Ele';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Ex Marido Bombeiro Queima De Arrependimento';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Atenção a Lenda Viva Saiu Da Prisão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O CAMINHO DA LIBERDADE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Disparo Do Destino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sr Silva, Você Escolheu A Pessoa Errada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MATHEUS SILVEIRA O BASTARDO QUE CALOU O REINO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Por Promessa Acidental';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A TUTORA E O REBELDE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Divórcio General De Rosto Frio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Capitão Deslumbrante Em Casada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Rotas Paralelas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Noiva Caipira Do Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Me Casei Com o CEO Misterioso';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'FLORES AO AMANHECER TARDE DEMAIS';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'CASO ENCERRADO O RETORNO DA RAINHA DO DIREITO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'De Volta Ao Coração Dela';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Pensamento Revelados';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Senhorita Renascida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MINHAS LÁGRIMAS SÃO ÁGUAS PASSADAS';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Coração Em duas Promessas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MAMÃE SOMOS QUADRIGÊMEOS';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O PREÇO DA OBSESSÃO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Encontrei Um Marido Bilionário e Sem Teto Para O Natal';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Na Ponta Da Faca O Retorno Do Rei Da Culinária';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Noiva Malvada VS. A Sogra Secreta';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Amor Desce Com Benção E Barriga';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Segredo Do Nosso Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'VOANDO COM VOCÊ';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'fingindo Ser Pobre';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Renascer Para Amar O Senhor Perfeito';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amo O jeito Que Você mente';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Guardião De Dia e Amantes A Noite';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Segredos do Pecado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Bilionário e a Amada Grávida Desaparecida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'De Solitária A Princesinha Da Casa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Eu Era Hetero Até O Beijo Dele';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Esperma Errado Amor Certo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Cego De Paixão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Reencarnação Do Imortal';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Coração De Ouro';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Ela Armou Ele Apaixonou';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Implacável';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Noiva Renegada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'LIGADA A HONRA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Esposa em Fuga, de Novo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Tão Frágil Tão Cor De Rosa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Minha Secretária a Mãe Do Bebê';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Grã Mestra';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Divorcio Para Ser A Herdeira';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Corações Em Contagem Regressivas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'PAPAI É O REI VAMPIRO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Melhor Amigo Do Meu Pai Me Fez Sua Esposa Bilionária';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Depois Da Tempestade';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Queda Da Noiva Mercenária';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'NOS BRAÇOS DO CHEFÃO DOMINANTE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Atormentada Pelo Amor Dele';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Divorciada No Dia Do Casamento';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Um Beijo Uma Facada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Relâmpago: Máscaras Caindo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Cura Do General';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Irmã Voltou Ajoelhem Se Todos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Herdeiro Perdido Nas Vésperas De Retomar Tudo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Bilionário Implacável';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Segredos de Uma Boa Moça';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Herdeira Retoma Seu Trono';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Último Eco Do Dragão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Jade Foster é Minha';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Refúgio Perigoso';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Herança Em Tempestade';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Vingança Da Herdeira Descartada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Depois Que A Sra Tirzah Brilhou Sozinha';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Princesa Da nova Família';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Do Lixo Ao  Luxo: Pais Bilionários Caindo Do Céu';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Corrida Para O Meu Coração';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Como Domar Uma Coroa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Renascida Para O Amor e Vingança';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Coroada De Amor: Sua Volta Por Cima Com Três Filhos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Pequeno Gênio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Entre a Neve e a Mentira';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Imperatriz Esquecida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Apaixonado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Divórcio Definitivo Seu Remorso Começou';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Adeus Que Sacudiu O Trono';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Superação e Ascensão: Rompendo os Céus';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Não Posso Esquecer Me De Ti';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Marido De Contrato é Um CEO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Amante Inocente Do Mafioso';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Após o Divercio a Dona De Casa Virou CEO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Entre O Amor e a Traição';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'NÃO QUERO MAIS VOCÊ A VINGANÇA DA EX ESPOSA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Jogo Do Destino Amor Após a Morte';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Quando a Lua Caiu';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Declarando Amor Através Da Névoa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Faxineira Milionária';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'EU NÃO QUERO O DIVÓRCIO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Apaixonando Se Pelo Marido Da Outra Mulher';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Reparando Um Amor Destruido Indesejado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DE MADRASTA A MÃE DE VERDADE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Herdeiro sob Cerco';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Perdido Na Neblina';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Depois De Uma Noite Quatro Bilionários Me Mimam';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor ao Primeiro Voo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Electra';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'De Gorducha a Arrasadora';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'ANOS 80 A GRANDE MUDANÇA DA ESPOSA GORDINHA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Nossa Culpa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MARIDO PEDE PERDÃO APÓS A TRANSFORMAÇÃO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Um Final Feliz Com o Imão Do Meu Noivo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amante Ladrão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Além Do Trabalho O Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Com licença Eu Sou O Big Boss';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Todo Poderoso';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'AMOR CALADO ÓDIO FINDO E O RESTO SEM LAÇO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'De Volta Ao Meu Brilho';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Minha Ex Mulher Flores Apos Divorcio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'CHEGA DE FINGIR NA VERDADE SOU SUA SOGRA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Keily';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Fortuna e Poder Em Minutos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Namoro De Mentira Com Meu Rico Inimigo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Capturar o Pai Milionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Ajustador';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Ilusório: O Preço Do Segredo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Laços Perigosos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Camponeses e Serpentes: A Fortuna Vira As Costas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Herdeira Supera O Seu Marido';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Filho Nao Quero Mais Trabalhar';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Um Pirralho Mimado Estraga Tudo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'GRAVIDEZ ACIDENTAL ROMANCE COM O CEO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sai Da Frente Sou a Ex Intocável';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Dupla Vida Do Senhor Presidente';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Corretora De Imóveis De Ouro';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Últimos 190 Minutos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Poder Do Conhecimento';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Modo Mae Ursa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Adeus Minha Tentadora Esposa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Renascer a Princesa Retorna';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Imperatriz Veio Trabalhar';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = '99 Amuletos 99 Desilusões';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'EXCITAR A ESPOSA VIRGEM DO MAFIOSO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Elas Por Elas Divorcio Ou morte';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Últimas Palavras do Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Perseguindo Minha Esposa Congelada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Magnata Presidente Se Apaixona Por Mim';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Bela Adormecida e Os Três Irmãos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Renascimento a Esposa do Padrinho';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Companheiro é Um Licano De Rua';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Retorno Da Medica Famosa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = '28 Dias Com O Alfa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Favoritismo mortal';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Herança e Vingança';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Liberte Me De Sua Traição';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Esposa Desaparecida Da Máfia Volta Com Gêmeos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'SEIS BEBÊ UM PAI BILIONÁRIO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Retorno Das Gêmeas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'OOPS EU TE AMO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Coroa Na Poeira a Ira Imperial ';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Último Testemunho Da Irmã';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'PAPAI NÃO VÁ! POR FAVOR SALVE A MAMÃE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Substituta Errada para o Bilionário Implacável';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Ex Mulher Rainha Da Ciência';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Alfa Não é meu Tipo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Doce Como Fogo, Amor Implacavel';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Retorno Da Garota Banida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O bebê Surpresa Da cinderela';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amaranhado de Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Pego No Ato';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'ELA NÃO É TÃO BOAZINHA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Entre a Névoa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Como Conquistar Um Raposa Prateada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = '30 Anos Congelada - 3 Irmãos Se Arrependem';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Santa Da Vingança [DUBLADO]';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Grávida De Gêmeos Do Bilionário O Amor Começa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Grávida do Meu Inimigo Mafioso';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Fogo Entre nós';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Para Ficar Ao Meu Lado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Beleza e vingança a Herdeira Inesperada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'PRINCESA INDOMÁVEL';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Caminho Para A Liberdade';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Virgem Do Vôlei De Praia';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Silenciado, A Reconciliação';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Arrependimento No Espelho';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DE PÉ MEU MARIDO BILIONÁRIO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Jogo Do Destino: Amor Após a Morte';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Esposa Injustiçada Do CEO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Esposa Feia Do Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MARIDO PEDE PERDÃO APÓS A TRANSFORMAÇÃO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Alfa Rei e sua Noiva Virgem';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Herdeiro de Seis Anos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Renascer Para Terminar Os Três Casamentos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sou Nada Mais Que Um Mortal';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Destinados a Perder a Luna Em Seus Sonhos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Renasci Após 8 Anos Para Fazer Meu  Pai Rico e Feliz';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Deisy Na Câmara Da Arma';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Segredo Do Bilionário Acompanhante';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Doutora E Seu Marido Secreto';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Largando o Astro Das Corridas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = '99 PROMESSAS DE UM AMOR UM ADEUS EM UM SEGUNDO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'TRAPAÇA FINA VINGANÇA DIVINA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Rosa Do Presidente Gustavo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Onde Termina o Contrato Começa O Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Minha Mãe é Uma Agente Secreta';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Vingança Silenciosa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Tirar As Notas e Acertar As Contas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Ficar Com Outras Mulheres Traz Poder';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Marido 200 Kg De Ódio Para Calcular';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Esposa Secreta Do Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Silêncio Do Coração';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Do Serviço Ao Sucesso';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'UM NEGÓCIO COM MEU DOADOR BILIONÁRIO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Olha O Que Você Me Fez Fazer';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Arte De Libertar Se';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'As Provas Do Amor no Tribunal';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Grávida Do rei Alpha, A Omega Que Ousou Desafiá lo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Coroa Reivindicada: Ela Ascende Da Traição';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Reunião Não é Retaliação';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'ARMADILHA PARA O CORAÇÃO DELE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Menina fica Viral Família Pede Perdão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Perdoar Pela Nonagésima Nona Vez';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sorria, Meu Marido Traidor, Está na Câmera';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Xiu Somos Um Secreto';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Dessa Vez Eu Escolhi Mafioso';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Namorado é Piloto Da Máfia';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Não Desperte O Dragão Dormindo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DESTINADA AO PAI ALFA DO MEU RIVAL';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Acertos De Contas Levanta Voo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Anos Perdidos, Como Se Fosse A Primeira Vez';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Mundo Termina Com Você';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Quatro Natais e Um Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Alma Delicada Coração Quebrado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Amante é Um Sniper';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Marido Frio, O Amor Ardente';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'FRIO NA ALMA  APÓS O AMOR E ÓDIO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'GENRO NÃO ELE É GUARDIÃO DOS TRÊS MUNDOS';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'UMA VÉSPERA DE ANO NOVO REAL';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Dia Em Que O Amor Morreu';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mamãe Não Fuja! Papai É Louco Por Você';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Rei Bastardo da Luta';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Coração Em jogo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Domando o Senhorio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Depois Da Florada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Você Não Vê Brilhando';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Divorciada e Desejada Pelo Trio De Pretendentes Da Elite';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Despedida Após 99 Vezes Perdão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Doutor Estou Pegando Fogo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Flor Proibida Minha Inimiga Meu Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Uma Aposta De Amor Ou Morte';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Entre Cinzas e Desejos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'SUBSTITUTA MAS QUE RENASCE NA SOMBRA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sou Nada Mais Que Um Mortal';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Companheira Amaldiçoada Do Alfa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mistério Da Senhora Rica';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Além Do Sol';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'VOZ INTERIOR DO BEBÊ AGARRA SE AS ABAS DO PAPAI';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Eu Dei a Minha Esposa Uma Arma Com Borlas Vermelhas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DEPOIS DO FINGIMENTO A PERDA ETERNA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'PS: Meu Barco De Amor De Amor Zarpou Sem Ti';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Fio Do Destino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sonho De Saudade Do Harém';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Gorda Que Mudou o Destino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Fazendo Campanha Pelo Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Ex Esposa De Face Dupla';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'IMPLORANDO À SUA ESPOSA HERDEIRA SECRETA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A PRINCESA REVERSA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'QUEIMANDO DE PAIXÃO PELO HOMEM QUE ELA AMAVA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Vingança Da Filha Libertada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Você Escolheu Seu Primeiro Amor Eu Escolhi Adeus';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Doce Como Tina';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Voltei Mas O Amor Nunca Foi Embora';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'ANTES DA TEMPESTADE O AMOR A DERIVA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Não Mexa Com Os Pais De Um Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O PLANO DA SENHORA NAN PARA ESCOLHER UM MARIDO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Segredos Da Orquídea';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Obesessão Agridoce';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Homem Por Trás Do Uniforme/Esse Segurança é Invencível/Imbatível Meu Guarda costas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Papai Gélido Não Fuja';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DEPOIS DA GEADA A ÚLTIMA LUZ';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Relâmpago Mimada Pelo Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Amor Que Perdi';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Bilionário e a Amada Grávida Desaparecida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Guerreira Esquecida [DUBLADO]';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Amante Contratada do Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Esperma Errado Amor Certo ll';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'In Die Liebe Gefallen/​Rush Into Love';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Jogo De Coroas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O MAGNATA QUE FINGIU SER MENDIGO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Doces Mentiras E Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Nova Vida Minha Liberdade';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Reivindicada Pelo Irmão Alfa do Meu Ex';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Justiça';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Tortura Delicada Da Mafia';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Pai Da Mafia E Os Seis Destinos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Senhor Governador Solte O Nosso Bebê';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Toda a Família Mima a Mimi';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Pobre Esposo É Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Esposa XXl Do Prefeito e Seu Retorno Incrível';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Segredo Sujo Do Meu Meio Irmão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Do Portão Ao Coração: Meu Papai é Um Abre Olhos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Babá Secreta Mãe Do Filho Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'PAI ENTREGADOR CHEFÃO OCULTO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Saia Da Frente Ex Intocável';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Jurei Te Amar Aprendi Te Largar';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Vingança Da Rainha Da Lei';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'APÓS A METAMORFOSE, O MARIDO IMPLORA PERDÃO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Chore Agora Saiba Quem Eu Sou';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Eu Salvei O Marido Alfa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Retorno do Deus Da Espada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Neto Falso Não Verdadeiro';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O MUNDO ME DEU VOCÊ';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Depois De Sair De Casa Ela Dá Uma guinada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'HERÓI DEVE NUNCA REBAIXAR-SE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento relâmpago a preferida do ceo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Seduzindo Melhor Amigo Do Meu Pai';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A mãe CEO e o Pai Incrível / Mamãe Ceo e o Papai  é Lider Da Guilda';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O AÇOUGUEIRO O SENHOR DAS ARTES MARCIAIS';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Esposa Virou Rainha Do Tribunal';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'De Sem-Teto À Esposa De Um Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casada Com Meu Chefe';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DEPOIS DO LEILÃO CASADA COM O INIMIGO DO MARIDO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Destino Selado Pacto Com O Rei Da Máfia';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = '99 PROMESSAS DE UM AMOR, UM ADEUS EM UM SEGUNDO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'NUNCA MAIS TE ESPEREI';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O RETORNO DE BRUNO FERREIRA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A noiva Proibida de Mancini';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Homem Que Estava ao Teu Lado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Adeus Em Silêncio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Eu Acidentalmente Roubei O Primeiro Beijo do Bady Boy';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Beije Me Uma Última Vez';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Herdeira Foi Trocada Ao Nascer';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Não Sintam Minha Falta Quando Eu Me For';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Queda Do Abusador/Abuser’s Dowbfall';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Beijei Um Sapo Consegui Um Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'COMO CONQUISTAR UM COROA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sai Da Minha Vida! Meu Primeiro amor acabou';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Renascido Em vingança';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O jogo Da Herança';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sem A Luz Da Lua Na Minha Terra';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'ESPOSA INESPERADA BELA ADORMECIDA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sinto Sua Falta Depois Do Adeus';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MEU PAI É O LENDÁRIO TITÃ';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'QUANDO MEU EX SE TORNA MEU GINECOLOGISTA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Rápido, Ela Não Segue As Regras Normais';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Fumaça Suave No Entardecer';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Chama Da Lua Entre Dois Alfas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Papai Malvado Você Tá Frito';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'AMOR JAMAIS PERDEU PARA MEMÓRIA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Ela Enlouqueceu O Pescoço é O Próximo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Lobo Divino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor, Morte e Ressurreição';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Outro Amor Fora do Tempo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Empregada Secreta Do General';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Que Chega Com Gravidez';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Drifit Tio Mecânico 2';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Dinheiro, Armas E Um Feliz Natal';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Querido Você Está Frito';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Para Sempre Ao Seu Lado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Jovem Santo Da Espada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Noiva Indesejada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Princesa Está De Volta';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Lapd Abra Seu Coração';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Virgem e o Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Quebrando Acordo Com o Badboy do Hóquei';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Não Desafie A Senhora Bilionária';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mudar Para o Interior Casar Com Um Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Obrigatório ? Me livro Com Três Damas Perdidas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MAIS FORTE QUE O DESTINO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Punida Pelo Seu Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casando Com O Herdeiro E Seu Bebê';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Do Peso a Glória';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Pai é O Chefão Da Secreto';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Contagem Da Vida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Depois Da Chuva Não houve Reencontro';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Uma Proposta Indecente';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Herdeira perdida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Pai Voltou todos Estão De Joelhos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Esposa Do CEO Venho Do Interior Para Te Apoiar';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu dom Da Riqueza';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'FALSA ESPERANÇA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Bilionário Em Fuga Torna Se Minha Noiva';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Vá Torcer Bebê';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Deusa Da Música';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sua Doce Bela';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'AMOR PROIBIDO EM TRÊS VIDAS';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'As Gêmeas e o Magnata';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Amor Nos Uniu De Novo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DO TIRO AO ALTAR AMOR PROIBIDO (DUBLADO)';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Em Nome Do Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sendo Madrasta, De volta Aos Anos 80';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Retorno do Jovem Mestre';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Ultimato Pela Cidade: Seu Remorso Na Pública';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Código da Honra';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Vingança Da Senhora';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Viciado Nela, A Querida Mimada Do CEO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A CEO Secreta';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Segredo Do Pai';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Alavancada No Jogo A Patroa De Cozinha Do Ceo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Último Adeus Ao Ente Querido';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'HERDEIRA ÚNICA NO MUNDO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Lâmina Perdida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'BRILHANTE VINGANÇA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Rebelde';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Te Amo Sem Razão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Um Acordo Com O Capitão Do Hóquei';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Retrocontagem do Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Abra Seus Olhos Meu Marido Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O HERDEIRO PERDIDO UMA VINGANÇA NATALÍCIA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'EMPATIA E EGOÍSMO A MULHER QUE CONDENOU A PRÓPRIA FILHA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Ascensão Do Pequeno Mestre';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Reencontro Do Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Médico Chefe é o Papai do meu Bebê';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Doçura Amarga De Vê la Divorciada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MINHA LUZ ALÉM DELE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Brilhei Na Festa Do Divorcio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Serva e o Tirano';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'VOO FATAL DESTINO REFEITO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Pai Segurança Pai Magnata';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mimada Ao Extremo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Quando A Neblina Levanta Me Ame';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Herdeira Grávida e Mimada Por 5 Tios Bilionários';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Herdeira Sheeran Retorna';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DOULAS DE 20 ANOS ELA VIROU MIMO DA FAMÍLIA RICA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'TARDE DEMAIS PARA UMA SEGUNDA CHANCE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'FORÇA SECRETA DA ESPOSA GORDINHA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Cego da Herdeira';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O AMOR É UMA DANÇA PERIGOSA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Como Largar Um Astro Do Roquei';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Medimos A Culpa Na Cama';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Verdadeiro Sem Magia';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Goleada Pelo Rival Do Meu Irmão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Odeio o Jeito Que Você Mente';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MAMÃE NÃO CHORE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MINHA ESPOSA SUPER PODEROSA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Encantada Pelos Gêmeos Bilionários';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Caminho Para A Escuridão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Marido Em Casa? Melhor Supremo Imortal';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Piloto De Oito Anos Rumo Ao Céu';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Jogo Do Carma';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'VOCÊ JÁ SE DIVORCIOU';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Segredo Do Poder Maldito';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sendo Mimada Pelo Marido CEO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MEU GATO BILIONÁRIO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Encontro Destinado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'QUANDO NOS REENCONTRARMOS';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Boa Menina Da Máfia';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Como Me Tornei Uma Herdeira Bilionária';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Relâmpago Com o CEO Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sob a Luz Das Flores Caixa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Aulas Particulares';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Devolva Meu Carro';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'MARIDO POBRE ERA BILIONÁRIO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Adeus Meu Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'BELEZA FRIA NOVA VIDA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Em Chamas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'REENCARNEI E CASEI DE NOVO MEU EX NOIVO SURTA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O SEGREDO DO ANJO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Quebrando O Taco';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'VÍNCULOS PROIBIDOS';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Renascida Para Ser Principal Herdeira';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O AMOR QUE EU PERDI';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento De Repente Filhos Do Segredos';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mãe Solteira Impressiona O Mundo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Uma Entrega do Bebê Ao Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A CIRURGIA DA ÚLTIMA CHANCE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'ATENÇÃO GAROTOS A BISAVÓ CHEGOU';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'PAI DO MEU NOIVO ME QUER';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'OBJEÇÃO A JUSTIÇA SEMPRE RETORNA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Destinada Ao Meu Garoto De Programa Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'ELE NÃO É SEU MARIDO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casada Por Acidente Com O Alfa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Grávida Pelo Pai Do Meu Ex';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Saia Da Frente Eu Sou O Chefe Final';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Lenda Do Líder Fili';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'IMORTAL CAÍDA O ARREPENDIMENTO DO IMPERADOR';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'EM NOME DO SEU BEM';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Ex Vilã Grávida Dá A Volta Por Cima';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Substituta Acidental Para Alfa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A CABULOSA HERDEIRA RETORNA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Marido De Aluguel';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'FILHA SORTUDA PAI NO TRONO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Inverno De Paixão No Grande Hotel';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Minha Irmã é Incrível';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Eu Beijei Um CEO e Ele Gostou Assim';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'CASAMENTO RELÂMPAGO COM ESPOSA LEGISTA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amigas No Livro Fuga e Pânico';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A FILHA DO INFERNO CHEGOU';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Adeus Sr Ex o Seu Comandante Está Chamando';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'De Capricho e Carinho Uma Aposta Bilionária De Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Chefe a Sua Estagiária é a Sua Esposa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DO DEMITIDO AO TEMIDO JAMAIS AO SEU ALCANCE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DO TRAMBOLHO AO TRIUNFO O DEVANEADOR POBRE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Grávida Do Ceo Mimada Pela Família';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'FLECHAÇO ENTRE LUZ E ESCURIDÃO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Aurora Oculta: O Governante Ascendente';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Vida Dupla De Um Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'mortal? Já Estive Lá, Fiz Isso';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Servente Supremo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Magnata Secreto, Amor Revelado';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Me Separei No Dia Do Parto';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mil Perdões e Um Incêndio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento às Pressas: O Amor de André e Bianca';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Dote Que Desfez O Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Minha Filha Me Chama de Tia(Sou Uma Filha Invisível)';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Apaixonada Pelo Melhor Amigo Do Meu Irmão';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Vida Secreta do Meu Marido Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Titânico Após O Renascimento';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Memória Perdida: A Vingança da CEO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Alfa Implacável Sem Saida';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'ENCONTRO ERRADO AMOR CERTO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Um Encontro Às Cegas Com Meu Novo Destino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Dispensaste Um Gênio Tecnológico';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'ADEUS AO QUE FOMOS';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DE BILIONÁRIO A PAI EM TEMPO INTEGRAL';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sobrenome Meu Glória Minha';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Vingança da Esposa CEO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O FADO DA MINHA IRMÃ QUE ME PERTENCE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Vingança Da Reencarnada, Troquei De Noivo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'DE NINGUÉM A QUERIDINHA DELE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Surpreendente Ela é Da Alta Sociedade';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Sem Ela Meu Mundo Desaba';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Minha Família Me Vendeu Para Um Chefe Do Crime';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Ceo Meu Milagre';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Noiva Virgem Do Alfa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Princesa Dos Lycan Nao Sera Sua Luna';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A RAINHA DIVORCIADA DA MARINHA DESPERTA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Arquiteto Do Destino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Helena Transmingou Para Um Romance';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Cai Perfeitamente Em Seus Braços';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Paixão Inesperada Do destino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'HERDEIRA VS IMPOSTORA NO JATO PRIVADO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A NOVA ESTAGIÁRIA SEGREDO PROIBIDO COM O CEO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Drift Tio Mecânico';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'OLHO DIVINO PODER SEM LIMITES';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Em Velocidades Perigosas';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Derruba A Familia Do descarado Com Minha Sogra';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Meu Principe Vamos Sair Do Armario';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A AMANTE SECRETA DO PODEROSO CHEFÃO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Última Batida Por Amor';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Renasci E Agora Eu Mando/ Novo Amanhecer/ Determinada E Forte';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'QUANDO O AMOR SE FAZ PRESENTE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Rejeitada Luna Voltou Com Um Filho';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Mamãe Não Chore Papai Esta Arrependido';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Três Erros e Meu Pai Tá Fora';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'TROCA DE NOIVOS O CEO INDECISO E O BILIONÁRIO SECRETO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Herdeira Bilionária Divorciada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'NOIVA TROCADA DO REI ALFA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Retorno aos 18 O Meu Reinado Sobre mil Terras';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Tortura Delicada Da Mafia';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'SONHOS QUE MATAM';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'No Dia Do Casamento Eu Desisti Dele';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'SOMBRAS DO PASSADO LUZ  DO AMOR';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'QUEM ME DERA QUE NÃO FOSSE VOCÊ';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Um Encontro Às Cegas Com Meu Destino';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Depois de Desmascarar a Falsa Amiga';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Retorno Da Fênix';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O AMOR DE PAI QUE A LEVANTOU';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'PAPAI ESSA CRIANÇA NEM É SUA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Velocidade Furiosa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Cartas de Amor Não Valem Nada';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Ascensão Da Princesa Traída';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Lenda Do Senhor Guerreiro';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Babá Ex Presidiária, Pai Solteiro Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Substituta Virgem do Bilionário';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A Bela Tímida e a Fera Bilionária';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'A BOLSISTA QUE CONQUISTOU A ESCOLA DAS ELITES';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'SUBI DE VIDA AO TER OS FILHOS DO CEO';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'SNIPER AMERICANO A ÚLTIMA RODADA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Conquistei um Bilionário Para Ser Meu Esposo';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Herdeira Verdadeira VS Rainha Falsa';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O Despertar Do Gênio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'PATRIARCA CRIADOR MEU SANGUE INVENCÍVEL';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Apos o Renascimento: Pelo Tio Mimada Meu Marido';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Casamento Relâmpago Esposa Tola, doce e Selvagem';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Não Ria! Ana Te Fez Assinar O Divorcio';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Criando O Filho Bastardo Do Meu Marido';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O DRAGÃO E SUA RAINHA PERDIDA';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O APOIO DE UM PAI';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Amor Cativo Do Chefe Da Máfia';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'CAPTURADA PELO JOGO DELE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'O BAD BOY E EU';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'OLHO CELESTIAL ABERTO TUDO SE SUBMETE';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Seu Amor Foi Um Sombra';
UPDATE filmes SET is_dubbed = TRUE WHERE titulo = 'Até Nos Encontrarmos Novamente';

SELECT 'Updated 875 movies to is_dubbed=TRUE' as status;